import { PipelineState } from '@/types/agent';
import { FileText, Download, Copy, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useState } from 'react';
import { toast } from 'sonner';

interface FinalReportProps {
  state: PipelineState;
}

const FinalReport = ({ state }: FinalReportProps) => {
  const [copied, setCopied] = useState(false);

  if (state.status !== 'complete' || !state.finalOutput) return null;

  const reportData = state.finalOutput.data as {
    title?: string;
    sections?: string[];
    recommendations?: string[];
    actionItems?: Array<{ priority: string; task: string }>;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(state.finalOutput, null, 2));
    setCopied(true);
    toast.success('Report copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([JSON.stringify(state.finalOutput, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'agent-report.json';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  return (
    <div className="bg-card rounded-xl border border-success/50 p-6 glow-success">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-success/20 flex items-center justify-center">
            <FileText className="w-5 h-5 text-success" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-foreground">{reportData.title || 'Final Report'}</h2>
            <p className="text-sm text-muted-foreground">Generated by Agent Pipeline</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload}>
            <Download className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Sections */}
      {reportData.sections && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-foreground mb-3">Report Sections</h3>
          <div className="flex flex-wrap gap-2">
            {reportData.sections.map((section, idx) => (
              <span key={idx} className="px-3 py-1 bg-secondary rounded-full text-xs text-foreground">
                {section}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Recommendations */}
      {reportData.recommendations && (
        <div className="mb-6">
          <h3 className="text-sm font-semibold text-foreground mb-3">Key Recommendations</h3>
          <ul className="space-y-2">
            {reportData.recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-muted-foreground">
                <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Action Items */}
      {reportData.actionItems && (
        <div>
          <h3 className="text-sm font-semibold text-foreground mb-3">Action Items</h3>
          <div className="space-y-2">
            {reportData.actionItems.map((item, idx) => (
              <div key={idx} className="flex items-center gap-3 p-3 bg-background rounded-lg border border-border">
                <span className={`px-2 py-0.5 rounded text-xs font-medium uppercase ${
                  item.priority === 'high' ? 'bg-destructive/20 text-destructive' :
                  item.priority === 'medium' ? 'bg-warning/20 text-warning' :
                  'bg-muted text-muted-foreground'
                }`}>
                  {item.priority}
                </span>
                <span className="text-sm text-foreground">{item.task}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default FinalReport;
